version: "3.4"

services:
  mongodb:
    image: mongo
    container_name: mongodb-rs
    # this host works for Windows by default.. that's why I chose this
    hostname: host.docker.internal
    volumes:
      - ./data/db/:/data/db/
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
      MONGO_REPLICA_SET_NAME: ${MONGO_REPLICA_SET_NAME}

    healthcheck:
      test: test $$(echo "rs.initiate().ok || rs.status().ok" | mongo -u $${MONGO_INITDB_ROOT_USERNAME} -p $${MONGO_INITDB_ROOT_PASSWORD} --quiet) -eq 1
      interval: 10s
      start_period: 30s

    command: ["--replSet", "${MONGO_REPLICA_SET_NAME}", "--bind_ip_all"]
    # windows users: comment out extra_hosts section
    # linux/mac/wsl users: make sure the extra_hosts section ISN'T commented out
    extra_hosts:
      host.docker.internal: 172.17.0.1
